BASE_URL = "https://www.saucedemo.com"
sauceDemo_login_xlsx = "data/sauceDemo_login.xlsx"
your_information_xlsx = "data/your_information.xlsx"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BUTTON_ID ="login-button"
ERROR_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
USERNAME_PASSWORD_EMPTY = "Epic sadface: Username is required"
PASSWORD_EMPTY = "Epic sadface: Password is required"
USERNAME_PASSWORD_DONT_MATCH = "Epic sadface: Sorry, this user has been locked out."
CLASS_NAME = "inventory_item"
WİNDOW_SCROLL = "window.scrollTo(0,500)"
WİNDOW_SCROLL2 = "window.scrollTo(500,0)"
BACK_PACK_ADD = "//*[@id='add-to-cart-sauce-labs-backpack']"
T_RED_ADD = "//*[@id='add-to-cart-test.allthethings()-t-shirt-(red)']"
CART_LİNK = "shopping_cart_link"
C_NAME = "cart_item"
CHECKOUT_ID = "checkout"
FIRST_NAME_ID = "first-name"
LAST_NAME_ID = "last-name"
POSTAL_CODE_ID = "postal-code"
CONTINUE_ID = "continue"
CONTINUE_XPATH = "//*[@id='checkout_info_container']/div/form/div[1]/div[4]/h3"
ERROR_POSTAL_CODE = "Error: Postal Code is required"
BACK_PACK_REMOVE = "//*[@id='remove-sauce-labs-backpack']"
T_RED_REMOVE =  "//*[@id='remove-test.allthethings()-t-shirt-(red)']"