# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtocart(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "login-button")))
    self.driver.find_element(By.ID, "login-button").click()
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    self.driver.find_element(By.ID, "add-to-cart-test.allthethings()-t-shirt-(red)").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'shopping_cart_container\']/a").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'cart_contents_container\']/div/div/div[3]/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'cart_contents_container\']/div/div/div[4]/div").click()
  
